### PR TITLE
Windows developer can run tests for this project

### PR DESCRIPTION
**Pull request by rwalle61**
As https://github.com/RuntimeTools/chai-openapi-response-validator/issues/30#issuecomment-566078318 shows, Windows developers should be able to run this project. 

I don't have a Windows machine but these changes allowed `npm run test:full` to succeed on a Windows 10 WM and also the Travis builds.

Changes:
* added travis job to build and test on windows with every PR
* removed eslint rule that errored on windows (linebreak-style), which does not seem necessary now that we are testing both macos and windows on travis (could test linux too, but I'm assuming testing macos is enough)
* upgraded nyc version because the current version was erroring on windows. See https://github.com/istanbuljs/nyc/issues/1205#issuecomment-552124764

### CODE REVIEW

**Comment by rwalle61** [comment]
Migrating discussion from https://github.com/RuntimeTools/chai-openapi-response-validator/issues/30#issuecomment-566290639:
> Thanks @rwalle61 – I was able to install the support-windows branch and run setup.test.js, definedServerPath.test.js and differentRequetModules.test.js. 
However, I could not execute satisfyApiSpec.test.js – not sure why, could be my IDE setup
Changing to directory test/unit/assertions and running > mocha satisfyApiSpec.test.js caused some errors because it could not resolve the 2 openapi files.

**Comment by rwalle61** [comment]
@GSDTN, could you post the errors you got trying
>However, I could not execute satisfyApiSpec.test.js – not sure why, could be my IDE setup
please?

I also get errors on mac if I try
>Changing to directory test/unit/assertions and running > mocha satisfyApiSpec.test.js caused some errors because it could not resolve the 2 openapi files.

(Although, don't have mocha globally installed so I did `../../../node_modules/mocha/bin/mocha`). 

I can see if there's a way to fix that, but in any case I think we need to see your errors that are unique to windows :)

**Comment by GSDTN** [comment]
I tried running the definedServerPath.test.js using mocha from the terminal and had a similar failure.
Those tests run within IntelliJ.  So the error on satisfyApiSpec I was seeing is likely more my approach to running the test than the test itself.

How would you recommend running the satisfyApiSpec test. Or all tests globally.

**Comment by rwalle61** [comment]
I agree with this:
>So the error on satisfyApiSpec I was seeing is likely more my approach to running the test than the test itself.

Re:
>How would you recommend running the satisfyApiSpec test. Or all tests globally.

`npm test` should work. (And it works on Travis. `npm run test:coverage` calls `npm test`, and `npm run test:full` calls `npm run test:coverage`)

**Comment by rwalle61** [comment]
@GSDTN unless you have objections I will merge this since this change might benefit some Windows developers. Happy to extend this to work for you too if we figure out what goes wrong when you run `npm test`

**Pull request merged**
